apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: ZmF6bGU=
  MYSQL_ROOT_PASSWORD: YmppdDEyMzQ= 
  MYSQL_PASSWORD: ZmF6bGUxMjM0
  MYSQL_DATABASE: c3BhcmtsbXNkYg==
